default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trailing Whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        name: End of File
        stages: [pre-commit]
      - id: check-yaml
        name: YAML Syntax
        stages: [pre-commit]
      - id: check-toml
        name: TOML Syntax
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-format
        name: Python Format
        stages: [pre-commit]
      - id: ruff
        name: Python Lint
        stages: [pre-commit]
        args: [--fix]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.1
    hooks:
      - id: commitizen
        name: Commit Linter
        stages: [commit-msg]
