name: topologyx

on: [pull_request, merge_group]

jobs:
  workflow:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ./.venv/
          key: topologyx-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Setup Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: poetry install --sync --with dev,types

      - name: Run Black
        run: make black

      - name: Run MyPy
        run: make mypy

      - name: Run Ruff
        run: make ruff
